### ISSUE TITLE
Evolve doesn't work when you do not have a toplevel pub spec.lock file

### ISSUE THREAD

**Issue by remonh87** [alexei-sintotski/dart-borg#84]
I have a monorepo containing of 9 packages but when I run `borg evolve --fluttersdk=<path> --dry-run`

I get the following output:
```
Scanning for Dart packages... 11 packages found
Resolving 33 direct external dependencies used by all found packages...
pubspec.yaml has no lower-bound SDK constraint.

You should edit pubspec.yaml to contain an SDK constraint:
environment:
  sdk: '>=2.10.0 <3.0.0'
```

I noticed borg for some reason finds 11 packages which is incorrect.

**Expected result**
Borg should only scan folders containing a pubspec.yaml file.

**Comment by alexei-sintotski** [comment]
@remonh87 I cannot reproduce this issue. Could you please add the -v/--verbose option to see found packages?

**Comment by remonh87** [comment]
it is magically solved I think it has to do that I start using `dart pub global run` since flutter pub global run has some weird issiues. Anyway fixed!

**Comment by remonh87** [comment]
I get now the same issue with boot. This is the command I did run. `flutter pub global run borg:main boot --verbose`

<details>
  <summary>Command output</summary>
  
 ```txt
[ +142 ms] executing: sysctl hw.optional.arm64
[  +34 ms] Exit code 0 from: sysctl hw.optional.arm64
[   +3 ms] hw.optional.arm64: 1
[  +10 ms] executing: [/Users/user/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[   +1 ms] executing: [/Users/user/flutter/] git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[  +66 ms] Exit code 0 from: git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[        ] 2.10.0
[  +12 ms] executing: [/Users/user/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/user/flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +166 ms] executing: [/Users/user/flutter/] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +33 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.6
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G165
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +48 ms] Using /Users/user/flutter/.pub-cache for the pub cache.
[        ] executing: /Users/user/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub global run borg:main boot --verbose
Scanning for Dart packages... 19 packages found

Analyzing workspace changes for incremental bootstrapping...

No information on the last successful bootstrapping is found.
Bootstrapping all found packages...

Bootstrapping packages:
[1/19] Flutter package apps/bonbot_app...
FATAL: Cannot bootstrap Flutter package /Users/user/projects/bonbot_app/apps/bonbot_app, path to Flutter SDK is not defined
[+2342 ms] "flutter global" took 2,483ms.
[  +24 ms] pub finished with exit code 255
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```
</details>

**Comment by alexei-sintotski** [comment]
@remonh87 It seems you did not define path to flutter SDK and yet are trying to bootstrap flutter packages. I would recommend you to
1. Create an init file with command `borg init`, and
2. Fill in path to flutter SDK to the field `flutter_sdk: ` in the newly created `borg.yaml` file.
Could you please check out whether this solution works?
Thank you!

As an improvement, I can change `borg` so that it can try to find flutter SDK on PATH if path to flutter SDK is undefined.

**Comment by alexei-sintotski** [comment]
@remonh87 BTW, the original issue was a different problem. It seems one of your pubspec.yaml files did not specify version of dart SDK. The problem here is that this message is coming from flutter pub, borg does check this constraint.

**Comment by remonh87** [comment]
that was It! 👍
