### ISSUE TITLE
Borg probe crashes on version 2.0.0.

### ISSUE THREAD

**Issue by remonh87** [alexei-sintotski/dart-borg#98]
I think it has to do sth with null-safety migration:

```txt
Null check operator used on a null value
#0      StringToDependencyType.parseDependencyType (package:pubspec_lock/src/package_dependency/dependency_type/serializers.dart:31:67)
#1      loadPathPackageDependency (package:pubspec_lock/src/package_dependency/path_package_dependency/serializers.dart:42:54)
#2      loadPackageDependency (package:pubspec_lock/src/package_dependency/serializers.dart:45:35)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#4      ExpandIterator.moveNext (dart:_internal/iterable.dart:475:32)
#5      SetMixin.addAll (dart:collection/set.dart:57:23)
#6      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:192:27)
#7      Iterable.toSet (dart:core/iterable.dart:486:21)
#8      findInconsistentDependencies (package:borg/src/find_inconsistent_dependencies.dart:43:62)
#9      ProbeCommandRunner._checkPubspecLockFiles (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/commands/probe_command_runner.dart:106:35)
#10     ProbeCommandRunner.run (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/commands/probe_command_runner.dart:70:7)
#11     ProbeCommand.run.<anonymous closure> (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/commands/probe_command.dart:59:11)
#12     exitWithMessageOnBorgException (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/utils/borg_exception.dart:44:11)
#13     ProbeCommand.run (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/src/commands/probe_command.dart:55:17)
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#16     new Future.sync (dart:async/future.dart:296:31)
#17     CommandRunner.run (package:args/command_runner.dart:119:14)
#18     main (file:///Users/user//flutter/.pub-cache/hosted/pub.dartlang.org/borg-2.0.0/bin/main.dart:44:9)
#19     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[+2329 ms] "flutter global" took 2,453ms.
```

**Comment by alexei-sintotski** [comment]
@remonh87  Could you please send me your pubspec.lock file and the corresponding pubspec.yaml file? I think you reproduced an issue I was chasing for months :) The failing dependency has very strange type I never encountered myself before. Thank you!

**Comment by remonh87** [comment]
I tried reproducing it but after flutter upgrade it works fine :( . I did trace back each commit and cannot see. why it suddenly work. To be honest I think we should close it

**Comment by remonh87** [comment]
@alexei-sintotski  I think I may found the cause for the crash:  there is a dependency called `direct overridden` . I saw it was crashing on that. For example:

```dart
common_utils:
     dependency: "direct overridden"
     dependency: transitive
     description:
       path: "../../utils/common_utils"
       relative: true
```
